[workspace]
members = [
    "docgen",
    "drivers/ahcid",
    "drivers/bgad",
    "drivers/e1000d",
    "drivers/pcid",
    "drivers/ps2d",
    "drivers/rtl8168d",
    "drivers/vesad",
    "drivers/xhcid",
    "installer",
    "kernel",
    "programs/acid",
    "programs/binutils",
    "programs/contain",
    "programs/coreutils",
    "programs/extrautils",
    "programs/games",
    "programs/init",
    "programs/ion",
    "programs/netutils",
    "programs/orbutils",
    "programs/pkgutils",
    "programs/smith",
    "programs/tar",
    "programs/userutils",
    "schemes/ethernetd",
    "schemes/orbital",
    "schemes/ptyd",
    "schemes/randd",
    "schemes/redoxfs",
]
